# Generated by Django 5.1.15 on 2026-03-27 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('value', models.CharField(help_text='Напр. "930+" або "19"', max_length=50, verbose_name='Значення')),
                ('description', models.CharField(max_length=200, verbose_name='Опис')),
                ('icon_svg', models.TextField(blank=True, verbose_name='SVG іконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Перевага',
                'verbose_name_plural': 'Переваги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('object_type', models.CharField(blank=True, max_length=200, verbose_name="Тип об'єкта")),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Зображення')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок')),
                ('cta_text', models.CharField(default="Зв'язатися", max_length=100, verbose_name='Текст кнопки')),
                ('cta_link', models.CharField(default='#contacts', max_length=200, verbose_name='Посилання кнопки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Слайд Hero',
                'verbose_name_plural': 'Слайди Hero',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва проєкту')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Опис')),
                ('category', models.CharField(choices=[('industrial', 'Промислове'), ('residential', 'Житлове'), ('commercial', 'Комерційне')], default='industrial', max_length=20, verbose_name='Категорія')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Партнерський проєкт',
                'verbose_name_plural': 'Партнерські проєкти',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PerspectiveInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ЖК у м. Васильків', max_length=200, verbose_name='Назва')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Локація')),
                ('hero_image', models.ImageField(blank=True, upload_to='perspectives/', verbose_name='Головне зображення')),
            ],
            options={
                'verbose_name': 'Перспективний проєкт',
                'verbose_name_plural': 'Перспективний проєкт',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('address', models.CharField(max_length=300, verbose_name='Адреса')),
                ('city', models.CharField(default='м. Вишгород', max_length=100, verbose_name='Місто')),
                ('status', models.CharField(choices=[('completed', 'Завершений'), ('in_progress', 'В процесі'), ('planned', 'Запланований')], default='completed', max_length=20, verbose_name='Статус')),
                ('year_completed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік завершення')),
                ('floors', models.CharField(max_length=50, verbose_name='Поверхи')),
                ('apartments_count', models.PositiveIntegerField(default=0, verbose_name='Кількість квартир')),
                ('total_area', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна площа, м²')),
                ('commercial_area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Комерційні площі, м²')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': "Об'єкт",
                'verbose_name_plural': "Об'єкти",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('icon_svg', models.TextField(blank=True, help_text='Inline SVG код', verbose_name='SVG іконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ЕЛІТ-ФАСАД ГРУП', max_length=200, verbose_name='Назва компанії')),
                ('slogan', models.CharField(blank=True, max_length=300, verbose_name='Слоган')),
                ('phone_main', models.CharField(max_length=30, verbose_name='Основний телефон')),
                ('phone_dev', models.CharField(blank=True, max_length=30, verbose_name='Телефон відділу розвитку')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='Логотип')),
                ('favicon', models.ImageField(blank=True, upload_to='site/', verbose_name='Favicon')),
                ('google_maps_embed_url', models.TextField(blank=True, verbose_name='Google Maps embed (iframe)')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('og_image', models.ImageField(blank=True, upload_to='site/', verbose_name='OG Image')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Номер кроку')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('icon_svg', models.TextField(blank=True, verbose_name='SVG іконка')),
            ],
            options={
                'verbose_name': 'Крок роботи',
                'verbose_name_plural': 'Кроки роботи',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='PerspectiveStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Назва')),
                ('value', models.PositiveIntegerField(verbose_name='Значення')),
                ('suffix', models.CharField(blank=True, help_text='м², га, шт', max_length=20, verbose_name='Суфікс')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('perspective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.perspectiveinfo', verbose_name='Проєкт')),
            ],
            options={
                'verbose_name': 'Статистика проєкту',
                'verbose_name_plural': 'Статистика проєктів',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Зображення')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Підпис')),
                ('category', models.CharField(choices=[('completed', "Збудовані об'єкти"), ('perspective', 'Перспективні проєкти')], max_length=20, verbose_name='Категорія')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project', verbose_name="Об'єкт")),
            ],
            options={
                'verbose_name': 'Зображення галереї',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Зображення')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Підпис')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Обкладинка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project', verbose_name="Об'єкт")),
            ],
            options={
                'verbose_name': "Фото об'єкта",
                'verbose_name_plural': "Фото об'єктів",
                'ordering': ['order'],
            },
        ),
    ]
