# Generated by Django 6.0.1 on 2026-03-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerproject',
            name='category',
            field=models.CharField(choices=[('industrial', 'Промислове'), ('residential', 'Житлове'), ('commercial', 'Комерційне'), ('cottage', 'Котеджні містечка')], default='industrial', max_length=20, verbose_name='Категорія'),
        ),
    ]
