# Generated by Django 6.0.1 on 2026-03-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_partnerproject_cottage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок блоку "Про нас"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_1',
            field=models.TextField(blank=True, verbose_name='Перший абзац "Про нас"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_2',
            field=models.TextField(blank=True, verbose_name='Другий абзац "Про нас"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='Про компанію', max_length=200, verbose_name='Заголовок блоку "Про нас"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_button',
            field=models.CharField(default='Отримати консультацію', max_length=100, verbose_name='Текст кнопки форми'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_text',
            field=models.CharField(default='Заповніть форму і наш менеджер зателефонує вам найближчим часом', max_length=300, verbose_name='Текст над формою'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_success_text',
            field=models.CharField(default="Наш менеджер зв'яжеться з вами найближчим часом.", max_length=300, verbose_name='Текст після відправки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_success_title',
            field=models.CharField(default='Дякуємо за звернення!', max_length=200, verbose_name='Заголовок після відправки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_subtitle',
            field=models.CharField(default="Залишилися питання? Зв'яжіться з нами", max_length=300, verbose_name='Секція "Контакти" — підзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_title',
            field=models.CharField(default='Контакти', max_length=200, verbose_name='Секція "Контакти" — заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='experience_subtitle',
            field=models.CharField(default='Проєкти, в яких ми брали участь', max_length=300, verbose_name='Секція "Досвід" — підзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='experience_title',
            field=models.CharField(default='Наш досвід', max_length=200, verbose_name='Секція "Досвід" — заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_title',
            field=models.CharField(default='Галерея', max_length=200, verbose_name='Секція "Галерея" — заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_subtitle',
            field=models.CharField(default='Збудовані житлові комплекси', max_length=300, verbose_name='Секція "Об\'єкти" — підзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_title',
            field=models.CharField(default="Наші об'єкти", max_length=200, verbose_name='Секція "Об\'єкти" — заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_title',
            field=models.CharField(default='Наші послуги', max_length=200, verbose_name='Секція "Послуги" — заголовок'),
        ),
    ]
