# Generated by Django 6.0.1 on 2026-03-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_about_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_tab_completed',
            field=models.CharField(default="Об'єкти Вишгород", max_length=100, verbose_name='Галерея — вкладка "Вишгород"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_tab_perspective',
            field=models.CharField(default='Перспективні проєкти', max_length=100, verbose_name='Галерея — вкладка "Перспективні"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_tab_realized',
            field=models.CharField(default="Реалізовані об'єкти", max_length=100, verbose_name='Галерея — вкладка "Реалізовані"'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('realized', "Реалізовані об'єкти"), ('completed', "Об'єкти Вишгород"), ('perspective', 'Перспективні проєкти')], max_length=20, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='projects_title',
            field=models.CharField(default="Власні об'єкти", max_length=200, verbose_name='Секція "Об\'єкти" — заголовок'),
        ),
    ]
