# Generated by Django 6.0.1 on 2026-04-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_gallery_tab_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='Аграрний сектор', max_length=200, verbose_name='Заголовок блоку "Про нас"'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Гранд Облік', max_length=200, verbose_name='Назва компанії'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='experience_subtitle',
            field=models.CharField(default='Повний супровід ФОП на будь-якій системі оподаткування', max_length=300, verbose_name='Секція "Досвід" — підзаголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='experience_title',
            field=models.CharField(default='Послуги для ФОП', max_length=200, verbose_name='Секція "Досвід" — заголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_maps_embed_url',
            field=models.TextField(blank=True, help_text='Лише адреса з атрибута src (https://…), без тегів iframe. Google Maps → Поділитися → Вставити карту → скопіювати src.', verbose_name='URL карти Google Maps'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='projects_subtitle',
            field=models.CharField(default='Відкриття, закриття та внесення змін', max_length=300, verbose_name='Секція "Об\'єкти" — підзаголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='projects_title',
            field=models.CharField(default='Реєстрація бізнесу', max_length=200, verbose_name='Секція "Об\'єкти" — заголовок'),
        ),
    ]
